---
title: "Wrangling + Graphs"
author: "Andrew Lai"
date: "08/04/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(tidyverse)
library(tidytext)
library(widyr)
library(ggraph)
library(igraph)
library(tidygraph)
library(plotly)
```

```{r, message=FALSE, warning=FALSE}
setwd("~/dataviz2021/Group_Project/Andrew_Text")
a2021 <- read_csv("airline2021.csv")
#a2015 <- read_csv("airlinetweets2015.csv")
```

```{r}
df <- a2021 %>%
  select(status_id,created_at,text,
         mentions_screen_name,location,retweet_count, hashtags)
```

```{r}
check <- df %>%
  mutate(mentions_screen_name = str_extract_all(mentions_screen_name, 
                                                '(?<=")[A-Za-z]+')) %>%
   unnest(., mentions_screen_name) %>%
  mutate(hashtags = str_extract_all(hashtags, '(?<=")[A-Za-z]+')) %>%
   unnest(., hashtags) %>%
  group_by(status_id) %>%
  mutate(mentions_screen_name =
           ifelse(is.na(mentions_screen_name),hashtags,mentions_screen_name)) %>%
  mutate(hashtags = 
           ifelse(is.na(hashtags), mentions_screen_name,hashtags)) %>%
  mutate(mentions_screen_name = tolower(mentions_screen_name))
```


```{r}
# Tweets that only reference on airline
clean <- check %>%
  filter(str_detect(mentions_screen_name, 
                    'alaska|delta|united|southwest|americanair')) %>%
  group_by(status_id) %>%
  mutate(n = n(),
         is_dupe = ifelse(n > 1,1,0)) %>%
  filter(is_dupe == 0) %>%
  filter(row_number()==1) %>%
  select(status_id,created_at,text,
         mentions_screen_name,location,retweet_count) %>%
  rename(airline = mentions_screen_name) %>%
  mutate(airline = case_when(airline == "alaskaair" ~ "Alaska",
                             airline %in% c("americanair","americanairlines",
                                            "americanairlnes") ~
                               "American",
                             airline %in% c("delta", "deltaairline") ~ "Delta",
                             airline == "southwestair" ~ "Southwest",
                             airline == "united" ~ "United")) %>%
  ungroup()
```

```{r}
tidy_2021 <- clean %>%
  mutate(text = tolower(text)) %>%
  unnest_tokens(output = word, input = text) %>% 
  anti_join(bind_rows(stop_words, data.frame(word = c("rt", "https"), 
                                             lexicon = "TWITTER")), 
            by = "word") %>%
  mutate(word =  gsub("[[:punct:][:blank:]]+", "", word)) %>%
  mutate(word = gsub("[0-9]+", "", word)) %>%
  mutate(word =  gsub("*\\b[[:alpha:]]{1,2}\\b *", "", word)) %>%
  mutate(word =  gsub("\\b[A-Z]+\\b", "", word)) %>%
  mutate(word = gsub("^ +| +$|( ) +", "\\1", word)) %>%
  mutate(word = str_replace(word,"alaska|delta|united|southwest|americanair","")) %>%
  
  filter(word != "") %>%
  count(airline, word, sort = TRUE) 
```

```{r}
total_2021 <- clean %>%
  mutate(text = tolower(text)) %>%
  unnest_tokens(output = word, input = text) %>% 
  anti_join(bind_rows(stop_words, data.frame(word = c("rt", "https"), 
                                             lexicon = "TWITTER")), 
            by = "word") %>%
  mutate(word =  gsub("[[:punct:][:blank:]]+", "", word)) %>%
  mutate(word = gsub("[0-9]+", "", word)) %>%
  mutate(word =  gsub("*\\b[[:alpha:]]{1,2}\\b *", "", word)) %>%
  mutate(word =  gsub("\\b[A-Z]+\\b", "", word)) %>%
  mutate(word = gsub("^ +| +$|( ) +", "\\1", word)) %>%
  mutate(word = str_replace(word,"alaska|delta|united|southwest|americanair","")) %>%
  
  filter(word != "") %>%
  count(airline, word, sort = TRUE) %>%
  group_by(airline) %>% 
  summarize(total = sum(n))
```

```{r}
tidy_2021 <- left_join(tidy_2021, total_2021, by = 'airline')
```


```{r}
valence <- inner_join(tidy_2021, get_sentiments("afinn"), by = "word")
violin_plot <- ggplot(valence, aes(x = airline, y = value, color = airline)) + 
  geom_violin( show.legend = FALSE) + 
  geom_boxplot(width=.1) +
  scale_y_continuous(breaks = seq(-5, 5, by = 1)) +
  labs(x = "Airlines", y = "AFINN Values") +
  ggtitle("Tweets Sentiment Value Distribution By Airlines") +
  theme(plot.title = element_text(vjust=2, hjust = 0.5),
        legend.position =  'none')

violin_plot
```


```{r}
weight_plot <- valence %>%
  mutate(Contribution = n * value) %>%
  rename(Freq = n) %>%
  rename(Polarity = value) %>%
  group_by(airline) %>%
  slice_head(n = 5) %>%
  arrange(((Contribution))) %>%
  mutate(word = reorder(word, Contribution)) %>%
  ggplot(aes(x = Contribution, y = reorder(word, Contribution), 
             fill = Contribution > 0, label = Freq, label1 = Polarity)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~airline, ncol = 2, scales = "free") +
  labs(x = "Sentiment Value * Number of Appearances",
       y = 'Top 5 Words From Tweets') +
  ggtitle("Sentiment Value Weighted by Frequency of Words in Tweets") +
  theme(plot.title = element_text(vjust=2, hjust = 0.5),
        axis.title.x = element_text(vjust = -5),
        axis.title.y = element_text(vjust = -5),
        legend.position =  'none')

weight_plot
```

```{r}
weight_plot_i <- 
  ggplotly(weight_plot, tooltip = c("contribution","label", "label1"))


```




```{r}
nrc_graph <- inner_join(tidy_2021, get_sentiments("nrc"), by = "word")
```

```{r}
emotion_plot <- nrc_graph  %>%
  group_by(airline, sentiment) %>%
  summarise(Freq=n(), .groups = 'drop') %>%
  ggplot(aes(Freq, reorder(sentiment, Freq), fill = airline)) +
  geom_col(show.legend = TRUE) +
  labs(x = "Frequency",
       y = 'Emotion Category',
       fill = "Airline") +
  ggtitle("Emotion Category by Frequency of Words in Tweets") +
  theme(plot.title = element_text(vjust=2, hjust = 0.5),
        axis.title.x = element_text(vjust = -1),
        axis.title.y = element_text(vjust = 1))

emotion_plot
```

```{r}
emotion_plot_int <- ggplotly(emotion_plot, tooltip = c("x"))


emotion_plot_int
```











```{r}
bing_graph <- inner_join(tidy_2021, get_sentiments("bing"), by = "word")

```

```{r}
bing_graph  %>%
  filter(sentiment == "positive") %>%
  filter(word != "trump") %>%
  group_by(airline) %>%
  slice_head(n = 5) %>%
  ggplot(aes(n, reorder(word, n), fill = airline)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~airline, ncol = 2, scales = "free")

```

```{r}
bing_graph  %>%
  filter(sentiment == "negative") %>%
  group_by(airline) %>%
  slice_head(n = 5) %>%
  ggplot(aes(n, reorder(word, n), fill = airline)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~airline, ncol = 2, scales = "free")

```




```{r}
textg <- word_cors %>%
    mutate(item1 = case_when(item1 == "alaskaair" ~ "AlaskaAir",
                             item1 %in% c("americanair","americanairlines",
                                            "americanairlnes") ~
                               "AmericanAir",
                             item1 %in% c("delta", "deltaairline") ~ "DeltaAir",
                             item1 == "southwestair" ~ "SouthwestAir",
                             item1 == "united" ~ "United")) %>%
    mutate(airline = case_when(item1 == "AlaskaAir" ~ "AlaskaAir",
                             item1 == "AmericanAir" ~ "AmericanAir",
                             item1 == "DeltaAir" ~ "DeltaAir",
                             item1 == "SouthwestAir" ~ "SouthwestAir",
                             item1 == "United" ~ "United")) %>%
  filter(airline %in% c("United", "SouthwestAir", "DeltaAir", 
                        "AlaskaAir", "AmericanAir")) %>%
  filter(correlation > 0.30) %>%
  graph_from_data_frame() 
```


```{r}
V(textg)$airline <- as.character(clean$airline[match(V(textg)$name, 
                                                 as.character(clean$airline))])

```

```{r}
g_tbl <- as_tbl_graph(textg1)
node_from <- g_tbl %>%
    as_tibble() %>%
    mutate(from = row_number())
new_g_tbl <- g_tbl %>%
    activate(edges) %>%
    left_join(node_from)
```

```{r, fig.height=3.75, fig.width=3.75}
set.seed(2021)
ggraph(textg, layout = "fr") +
  geom_edge_link(aes(edge_alpha = correlation), show.legend = FALSE) +
  geom_node_point(aes(color = airline), size = 5) + 
  geom_node_text(aes(label = name), repel = TRUE) +
  ggtitle("Word Correlation Network By Airlines") + 
  theme(panel.background = element_blank(),
        strip.background = element_rect(colour=NA, fill=NA),
        legend.position =  'none',
        plot.title = element_text(vjust=2, hjust = 0.5))
```

```{r}
airline_tf_idf <- tidy_2021 %>%
  bind_tf_idf(word, airline, n)
```

```{r}
airline_tf_idf %>%
  group_by(airline) %>%
  slice_max(tf_idf, n = 5) %>%
  ungroup() %>%
  ggplot(aes(tf_idf, fct_reorder(word, tf_idf), fill = airline)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~airline, ncol = 2, scales = "free") +
  scale_x_continuous(labels = scales::number_format(accuracy = 0.001,
                                 decimal.mark = '.')) +
  labs(x = "Term Frequency–Inverse Document Frequency",
       y = 'Top 5 Words From Tweets') +
  ggtitle("TF-IDF Score by Airline Tweets") +
  theme(plot.title = element_text(vjust=2, hjust = 0.5),
        axis.title.x = element_text(vjust = -1),
        axis.title.y = element_text(vjust = 1))
```


```{r}
word_cors <- clean %>%
  mutate(section = row_number() %/% 10) %>%
  filter(section > 0)  %>%
  unnest_tokens(output = word, input = text) %>% 
  anti_join(bind_rows(stop_words, data.frame(word = c("rt", "https"), 
                                             lexicon = "TWITTER")), 
            by = "word") %>%
  mutate(word =  gsub("[[:punct:][:blank:]]+", "", word)) %>%
  mutate(word = gsub("[0-9]+", "", word)) %>%
  mutate(word =  gsub("*\\b[[:alpha:]]{1,2}\\b *", "", word)) %>%
  mutate(word =  gsub("\\b[A-Z]+\\b", "", word)) %>%
  mutate(word = gsub("^ +| +$|( ) +", "\\1", word)) %>%
  filter(word != "") %>%   
  group_by(word) %>%
  filter(n() >= 20) %>%
  pairwise_cor(word, section, sort = TRUE) 

```


```{r}
textg <- word_cors %>%
    mutate(item1 = case_when(item1 == "alaskaair" ~ "AlaskaAir",
                             item1 %in% c("americanair","americanairlines",
                                            "americanairlnes") ~
                               "AmericanAir",
                             item1 %in% c("delta", "deltaairline") ~ "DeltaAir",
                             item1 == "southwestair" ~ "SouthwestAir",
                             item1 == "united" ~ "United")) %>%
    mutate(airline = case_when(item1 == "AlaskaAir" ~ "AlaskaAir",
                             item1 == "AmericanAir" ~ "AmericanAir",
                             item1 == "DeltaAir" ~ "DeltaAir",
                             item1 == "SouthwestAir" ~ "SouthwestAir",
                             item1 == "United" ~ "United")) %>%
  filter(airline %in% c("United", "SouthwestAir", "DeltaAir", 
                        "AlaskaAir", "AmericanAir")) %>%
  filter(correlation > 0.30) %>%
  graph_from_data_frame() 
```


```{r}
V(textg)$airline <- as.character(clean$airline[match(V(textg)$name, 
                                                 as.character(clean$airline))])

```

```{r}
g_tbl <- as_tbl_graph(textg1)
node_from <- g_tbl %>%
    as_tibble() %>%
    mutate(from = row_number())
new_g_tbl <- g_tbl %>%
    activate(edges) %>%
    left_join(node_from)
```

```{r, fig.height=3.75, fig.width=3.75}
set.seed(2021)
ggraph(textg, layout = "fr") +
  geom_edge_link(aes(edge_alpha = correlation), show.legend = FALSE) +
  geom_node_point(aes(color = airline), size = 5) + 
  geom_node_text(aes(label = name), repel = TRUE) +
  ggtitle("Word Correlation Network By Airlines") + 
  theme(panel.background = element_blank(),
        strip.background = element_rect(colour=NA, fill=NA),
        legend.position =  'none',
        plot.title = element_text(vjust=2, hjust = 0.5))
```


